theme:
title: Welcome to Pt!
description: Personal Homepage and Posts
icon: /assets/images/icon-rick.png

show_downloads: false
google_analytics: G-W9EF2VS3C2

plugins:
  - jemoji

collections:
  drafts:
    output: true

defaults:
  -
    scope:
      path: "collections/_posts"
    values:
      layout: post
  -
    scope:
      path: "collections/_drafts"
    values:
      layout: post

collections_dir: collections